// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlz1A87Fay86XVSwr1Jd6eN8qZ1YOefnI',
    appId: '1:1044871462418:web:a96278f841bb8c11caa2cb',
    messagingSenderId: '1044871462418',
    projectId: 'flutter-exercise-fajardo',
    authDomain: 'flutter-exercise-fajardo.firebaseapp.com',
    storageBucket: 'flutter-exercise-fajardo.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7RWt6CpQKF8769P9JyK1QetSTKAVExcE',
    appId: '1:1044871462418:android:5578c8b5f675a1fecaa2cb',
    messagingSenderId: '1044871462418',
    projectId: 'flutter-exercise-fajardo',
    storageBucket: 'flutter-exercise-fajardo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCa8zw1-Ilz-LfmGBJ-c2VfQPOVFytc0Bo',
    appId: '1:1044871462418:ios:325b051cdc5b4beccaa2cb',
    messagingSenderId: '1044871462418',
    projectId: 'flutter-exercise-fajardo',
    storageBucket: 'flutter-exercise-fajardo.appspot.com',
    iosBundleId: 'com.example.flutterExercise',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCa8zw1-Ilz-LfmGBJ-c2VfQPOVFytc0Bo',
    appId: '1:1044871462418:ios:c65bd3bfe2e68df2caa2cb',
    messagingSenderId: '1044871462418',
    projectId: 'flutter-exercise-fajardo',
    storageBucket: 'flutter-exercise-fajardo.appspot.com',
    iosBundleId: 'com.example.flutterExercise.RunnerTests',
  );
}
